name: Build
permissions:
  contents: write

on:
  push:
  pull_request:
    branches:
      - main

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-steamlink:
    uses: ./.github/workflows/build-steamlink.yml

  build-windows-macos:
    uses: ./.github/workflows/build-win-mac.yml

  create_release:
    name: Create GitHub Release
    needs: [build-steamlink, build-windows-macos]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./release-assets
          merge-multiple: true
          skip-decompress: true

      - name: Release Assets
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: ./release-assets/*